version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  win-build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: go build cmd/daemon/main.go
  publish-latest:
    environment:
      IMAGE_NAME: diane/gvd
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t diane/gvd:latest -f build/gvd/Dockerfile .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - publish-latest:
          filters:
            branches:
              only: master
