version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  win-build:
    environment:
      PKG_CONFIG_PATH: /tmp/pkg-config
      CGO_LDFLAGS: -L/tmp/ffmpeg-latest-win64-dev/lib/ -lavcodec -lavformat -lavutil -lswscale -lswresample -lavdevice -lavfilter
      CGO_CFLAGS: -I/tmp/ffmpeg-latest-win64-dev/include -w
      LD_LIBRARY_PATH: /tmp/ffmpeg-latest-win64-dev/lib

    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: choco install mingw pkgconfiglite
      - run:
          name: Setup pkg-config stubs
          command: ./build/windows/configure.sh
      - run:
          name: Install MinGW
          command: choco install mingw
      - run:
          name: Download FFMPEG-dev
          command: curl https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-latest-win64-dev.zip > /tmp/ffmpeg-latest-win64-dev.zip
      - run:
          name: Extract FFMPEG-dev
          command: unzip /tmp/ffmpeg-latest-win64-dev.zip -d /tmp/
      - run:
          name: Build Daemon
          command: go build -o=daemon.exe cmd/daemon/main.go
      - store_artifacts:
          path: daemon.exe
          destination: daemon.exe
  docker-build:
    environment:
      IMAGE_NAME: diane/gggv
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t diane/gggv:latest -f build/gggv/Dockerfile .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  release:
    jobs:
      - win-build:
          filters:
            branches:
              only: master
      - docker-build:
          filters:
            branches:
              only: master
